name: Rooted Android Emulator with Web Access

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  rooted_emulator:
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create rooted AVD
      uses: reactivecircus/android-emulator-runner@v2
      id: emulator
      with:
        api-level: 30
        arch: arm64-v8a  # Changed to ARM64 for Apple Silicon compatibility
        profile: "Nexus 5X"
        force-avd-creation: true
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -read-only -writable-system
        disable-animations: true
        script: |
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          echo "Rooting emulator..."
          adb root
          adb remount
          adb shell avbctl disable-verification
          adb reboot
          echo "Waiting for reboot..."
          adb wait-for-device
          adb root
          adb remount
          echo "Emulator rooted"

    - name: Install SuperSU
      run: |
        # Download and install SuperSU
        wget https://github.com/Chainfire/SuperSU/raw/master/arm64/supersu.zip -O supersu.zip
        unzip supersu.zip
        adb push arm64/su /system/xbin/su
        adb shell chmod 0755 /system/xbin/su
        adb shell su --install
        adb shell su --daemon&
        adb install Superuser.apk

    - name: Install APKs
      run: |
        adb install app-debug.apk
        adb install tcpdump.apk
        adb install scrcpy.apk

    - name: Start network monitoring
      run: |
        adb shell su -c "tcpdump -i any -s 0 -w /sdcard/network.pcap &"
        echo "Network monitoring started"

    - name: Setup web access
      run: |
        # Install noVNC and websockify
        brew install novnc websockify
        
        # Start scrcpy with websocket
        adb forward tcp:8888 localabstract:scrcpy
        websockify --web /usr/local/share/novnc 6080 localhost:8888 &
        
        # Start HTTP server for network logs
        python3 -m http.server 8000 &
        
        echo "Web interface available at: http://localhost:6080/vnc.html"
        echo "Network logs available at: http://localhost:8000/network.pcap"

    - name: Keep alive for debugging
      run: |
        echo "The emulator will remain active for 30 minutes for debugging"
        sleep 1800
