name: Rooted Android Emulator with Web Access

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  rooted_emulator:
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Added required distribution
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create rooted AVD
      uses: reactivecircus/android-emulator-runner@v2
      id: emulator
      with:
        api-level: 30
        arch: x86_64
        profile: "Nexus 5X"
        force-avd-creation: true
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -read-only -writable-system
        disable-animations: true
        script: |
          echo "Rooting emulator..."
          adb root
          adb remount
          adb shell avbctl disable-verification
          adb reboot
          sleep 30
          adb root
          adb remount
          adb push superuser.apk /system/app/
          adb shell settings put global package_verifier_enable 0
          echo "Emulator rooted"

    - name: Install required files
      run: |
        # Download necessary files
        wget https://example.com/superuser.apk  # Replace with actual SuperSU or Magisk
        wget https://example.com/tcpdump.apk
        wget https://example.com/scrcpy.apk

    - name: Install APKs
      run: |
        adb install superuser.apk
        adb install tcpdump.apk
        adb install scrcpy.apk
        adb install app-debug.apk  # Your APK file

    - name: Start services and monitoring
      run: |
        # Start tcpdump
        adb shell "su -c 'tcpdump -i any -s 0 -w /sdcard/network.pcap &'"
        
        # Setup port forwarding
        adb forward tcp:8888 localabstract:scrcpy
        
        # Install and start web services
        brew install novnc websockify
        websockify --web /usr/local/share/novnc 6080 localhost:8888 &
        python3 -m http.server 8000 &

    - name: Wait for connections
      run: |
        echo "Emulator is ready for connection"
        echo "VNC Web URL: http://localhost:6080/vnc.html"
        echo "Network logs: http://localhost:8000/network.pcap"
        echo "Maintaining connection for 30 minutes..."
        sleep 1800
