name: Build QEMU WebAssembly (Advanced)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        target: ["i386-softmmu", "x86_64-softmmu"]
    env:
      QEMU_VERSION: "9.2.0"
      EMSDK_VERSION: "latest"
      ARTIFACT_RETENTION_DAYS: 7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 libsdl2-dev libglib2.0-dev libpixman-1-dev ninja-build

      - name: Cache Emscripten SDK
        id: cache-emsdk
        uses: actions/cache@v3
        with:
          path: emsdk
          key: emsdk-${{ runner.os }}-${{ env.EMSDK_VERSION }}-v2
          restore-keys: |
            emsdk-${{ runner.os }}-

      - name: Install Emscripten
        run: |
          if [ ! -d "emsdk" ]; then
            echo "Cloning Emscripten SDK..."
            git clone https://github.com/emscripten-core/emsdk.git
          fi
          cd emsdk
          if [ ! -d "upstream/emscripten" ]; then
            echo "Installing Emscripten ${{ env.EMSDK_VERSION }}..."
            ./emsdk install ${{ env.EMSDK_VERSION }} || {
              echo "Failed to install Emscripten, retrying once..."
              ./emsdk install ${{ env.EMSDK_VERSION }}
            }
          else
            echo "Emscripten directory exists, updating via git..."
            git pull || echo "Git pull failed, proceeding with existing version..."
          fi
          echo "Activating Emscripten ${{ env.EMSDK_VERSION }}..."
          ./emsdk activate ${{ env.EMSDK_VERSION }}
          echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
          source ./emsdk_env.sh
          echo "Emscripten version: $(emcc --version)"
        working-directory: .
        timeout-minutes: 15

      - name: Cache QEMU Source
        id: cache-qemu
        uses: actions/cache@v3
        with:
          path: qemu-${{ env.QEMU_VERSION }}
          key: qemu-${{ env.QEMU_VERSION }}-${{ runner.os }}
          restore-keys: |
            qemu-${{ env.QEMU_VERSION }}-${{ runner.os }}

      - name: Download QEMU Source
        if: steps.cache-qemu.outputs.cache-hit != 'true'
        run: |
          echo "Attempting to download QEMU ${{ env.QEMU_VERSION }}..."
          wget --timeout=300 --tries=3 https://download.qemu.org/qemu-${{ env.QEMU_VERSION }}.tar.xz || {
            echo "Error: Failed to download qemu-${{ env.QEMU_VERSION }}.tar.xz."
            echo "Check version availability at https://download.qemu.org/."
            echo "Available versions might include 9.2.0 (Dec 2024) or newer."
            exit 1
          }
          tar -xf qemu-${{ env.QEMU_VERSION }}.tar.xz
          echo "QEMU source downloaded and extracted successfully."
        timeout-minutes: 10

      - name: Patch QEMU Configure Script
        run: |
          cd qemu-${{ env.QEMU_VERSION }}
          echo "Patching configure script to bypass host OS check for emcc..."
          sed -i '/Unrecognized host OS/ { s/error_exit/#error_exit/; s|$|\necho "Forcing host OS to linux for Emscripten build"\nhost_os=linux|; }' configure
          grep -A 5 "Unrecognized host OS" configure  # Verify patch
        working-directory: .

      - name: Configure QEMU
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemu-${{ env.QEMU_VERSION }}
          echo "Debug: Host OS reported as $(uname -s)"
          echo "Debug: Emscripten version $(emcc --version)"
          CONFIGURE_CMD="./configure --target-list=${{ matrix.target }} --cc=emcc --cxx=em++ \
            --disable-linux-user \
            --extra-cflags='-s USE_SDL=2 -s ASSERTIONS=1 -s SAFE_HEAP=1' \
            --extra-ldflags='-s USE_SDL=2 -s EXPORTED_FUNCTIONS=[_main] -s EXPORTED_RUNTIME_METHODS=[ccall,cwrap] -s ALLOW_MEMORY_GROWTH=1'"
          echo "Running: $CONFIGURE_CMD"
          eval "$CONFIGURE_CMD"
          echo "QEMU configured for target: ${{ matrix.target }}"
        working-directory: .

      - name: Build QEMU
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemu-${{ env.QEMU_VERSION }}
          emmake make -j2 V=1
          echo "QEMU build completed for target: ${{ matrix.target }}"
        working-directory: .
        timeout-minutes: 15

      - name: Test QEMU Binary
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemu-${{ env.QEMU_VERSION }}/${{ matrix.target }}
          ls -la
          if [ ! -f "qemu-system-${{ matrix.target }}" ]; then
            echo "Error: QEMU binary not found!"
            exit 1
          fi
          echo "Testing QEMU binary for target: ${{ matrix.target }}"
          node --version
          node qemu-system-${{ matrix.target }} --version || echo "Test failed, but continuing..."
        working-directory: .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-wasm-${{ matrix.target }}
          path: qemu-${{ env.QEMU_VERSION }}/${{ matrix.target }}/qemu-system-${{ matrix.target }}.*
          if-no-files-found: error
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: Cleanup
        run: |
          echo "Cleaning up build files..."
          rm -rf qemu-${{ env.QEMU_VERSION }}
          rm -rf emsdk
          echo "Cleanup completed."

      - name: Notify Build Status
        if: always()
        run: |
          echo "Build completed for ${{ matrix.target }} with status: ${{ job.status }}"
