name: Build QEMU WebAssembly (.wasm only)
on: [push]
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        target: ["i386-softmmu", "x86_64-softmmu"]
    env:
      EMSDK_VERSION: "latest"
      ARTIFACT_RETENTION_DAYS: 7
      PYTHON_VERSION: "2.7.18"  # Last Python 2.7 release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsdl2-dev libglib2.0-dev libpixman-1-dev ninja-build zlib1g-dev libfdt-dev libcap-dev libattr1-dev \
            wget libssl-dev libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev libncursesw5-dev xz-utils tk-dev

      - name: Install Python 2.7 from Source
        run: |
          wget https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz
          tar -xzf Python-${{ env.PYTHON_VERSION }}.tgz
          cd Python-${{ env.PYTHON_VERSION }}
          ./configure --enable-optimizations
          make -j$(nproc)
          sudo make altinstall  # Install as python2.7, not overwriting system python
          sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python2.7
          python2.7 --version

      - name: Cache Emscripten SDK
        id: cache-emsdk
        uses: actions/cache@v3
        with:
          path: emsdk
          key: emsdk-${{ runner.os }}-${{ env.EMSDK_VERSION }}-v2
          restore-keys: |
            emsdk-${{ runner.os }}-

      - name: Install Emscripten
        run: |
          if [ ! -d "emsdk" ]; then
            git clone https://github.com/emscripten-core/emsdk.git
          fi
          cd emsdk
          ./emsdk install ${{ env.EMSDK_VERSION }}
          ./emsdk activate ${{ env.EMSDK_VERSION }}
          echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
          source ./emsdk_env.sh
          echo "Emscripten version: $(emcc --version)"
        working-directory: .
        timeout-minutes: 15

      - name: Test Emscripten Environment
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          emcc --version || { echo "Emscripten not working!"; exit 1; }
          which emconfigure || { echo "emconfigure not found!"; exit 1; }

      - name: Fetch QEMU Source from qemujs-builder
        run: |
          git clone https://github.com/atrosinenko/qemujs-builder.git
          cd qemujs-builder
          git submodule update --init qemu || {
            echo "Error: Submodule update failed!"
            exit 1
          }
          cd qemu
          git checkout 62e5ad0178b6cee9a81cf16e939675855e85a68b

      - name: Configure QEMU
        id: configure
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemujs-builder/qemu
          echo "Configuring QEMU for ${{ matrix.target }}..."
          emconfigure ./configure --python=/usr/bin/python2.7 --target-list=${{ matrix.target }} --disable-xen || {
            echo "Configure failed!"
            exit 1
          }
          echo "CONFIGURE_SUCCEEDED=true" >> $GITHUB_ENV

      - name: Build QEMU WebAssembly
        if: env.CONFIGURE_SUCCEEDED == 'true'
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemujs-builder/qemu
          echo "Building QEMU .wasm for ${{ matrix.target }}..."
          emmake make -j2 V=1 CFLAGS="-s USE_SDL=2 -s ASSERTIONS=1 -s SAFE_HEAP=1" LDFLAGS="-s USE_SDL=2 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1"
          if [ ! -f "${{ matrix.target }}/qemu-system-${{ matrix.target }}.wasm" ]; then
            echo "Error: .wasm file not generated!"
            exit 1
          fi
          echo "Built .wasm file:"
          ls -lh ${{ matrix.target }}/qemu-system-${{ matrix.target }}.wasm
        timeout-minutes: 15

      - name: Upload .wasm Artifact
        if: env.CONFIGURE_SUCCEEDED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: qemu-wasm-${{ matrix.target }}
          path: qemujs-builder/qemu/${{ matrix.target }}/qemu-system-${{ matrix.target }}.wasm
          if-no-files-found: error
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: Cleanup
        run: |
          rm -rf qemujs-builder emsdk Python-${{ env.PYTHON_VERSION }} Python-${{ env.PYTHON_VERSION }}.tgz

      - name: Notify Build Status
        if: always()
        run: |
          echo "Build-wasm completed for ${{ matrix.target }} with status: ${{ job.status }}"
