name: Build QEMU WebAssembly for Android VM
on: [push, workflow_dispatch]
jobs:
  build-qemu-wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      QEMU_VERSION: "9.2.0"
      EMSCRIPTEN_VERSION: "latest"
      BUILD_DIR: "qemu-build-wasm"
      OUTPUT_DIR: "qemu-wasm-dist"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            git \
            python3 \
            python3-pip \
            ninja-build \
            libglib2.0-dev \
            libpixman-1-dev \
            libsdl2-dev \
            pkg-config \
            wget \
            xz-utils
          sudo pip3 install meson==1.5.0

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: 'emsdk_cache'

      - name: Download QEMU Source
        run: |
          wget -q --show-progress https://download.qemu.org/qemu-${{ env.QEMU_VERSION }}.tar.xz
          tar -xf qemu-${{ env.QEMU_VERSION }}.tar.xz
          mv qemu-${{ env.QEMU_VERSION }} qemu-src
          rm qemu-${{ env.QEMU_VERSION }}.tar.xz

      - name: Patch QEMU Source
        run: |
          cd qemu-src
          # Fix the pkgconfig deprecation warning
          sed -i "s/'pkgconfig'/'pkg-config'/g" meson.build
          
          # Apply any Android VM specific patches here
          # For example:
          # patch -p1 < ../patches/android-vm.patch

      - name: Configure QEMU for WASM
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cd ${{ env.BUILD_DIR }}
          
          # Create corrected Emscripten cross-compilation file
          cat > emscripten-cross.txt << 'EOF'
          [binaries]
          c = 'emcc'
          cpp = 'em++'
          ar = 'emar'
          strip = 'emstrip'
          pkg-config = 'pkg-config'
          
          [properties]
          needs_exe_wrapper = true
          
          [host_machine]
          system = 'emscripten'
          cpu_family = 'wasm'
          cpu = 'wasm32'
          endian = 'little'
          EOF
          
          # Correct Meson configuration for QEMU
          meson setup ../qemu-src \
            --cross-file emscripten-cross.txt \
            -Dtarget_list=i386-softmmu \
            -Dsdl=enabled \
            -Dspice=disabled \
            -Dxen=disabled \
            -Dkvm=disabled \
            -Dvnc=disabled \
            -Ddocs=disabled \
            -Dtools=disabled \
            -Dguest_agent=disabled \
            -Db_lto=true \
            -Doptimization=3 \
            -Ddebug=false \
            -Dstrip=true \
            -Db_pie=false

      - name: Build QEMU
        run: |
          cd ${{ env.BUILD_DIR }}
          ninja -v
          
          # Verify the build output
          if [ -f "qemu-system-i386" ]; then
            echo "QEMU i386 build successful"
            # Rename to .wasm for clarity
            mv qemu-system-i386 qemu-system-i386.wasm
            ls -lh qemu-system-i386.wasm
          else
            echo "Error: QEMU build failed"
            exit 1
          fi

      - name: Prepare Distribution Package
        run: |
          mkdir -p ${{ env.OUTPUT_DIR }}
          
          # Find and copy all generated files
          find ${{ env.BUILD_DIR }} -name 'qemu-system-*' -exec cp {} ${{ env.OUTPUT_DIR}} \;
          
          # Create loader script
          cat > ${{ env.OUTPUT_DIR }}/run-qemu.sh << 'EOF'
          #!/bin/bash
          echo "Running QEMU WASM..."
          node qemu-system-i386.wasm "$@"
          EOF
          chmod +x ${{ env.OUTPUT_DIR }}/run-qemu.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-wasm-android-vm
          path: ${{ env.OUTPUT_DIR }}/*
          if-no-files-found: error
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          rm -rf qemu-src ${{ env.BUILD_DIR }} ${{ env.OUTPUT_DIR }}
