Executing subproject gvdb 

gvdb| Project name: gvdb
gvdb| Project version: 0.0
gvdb| C compiler for the host machine: /home/runner/work/AVM/AVM/emsdk/upstream/emscripten/emcc (emscripten 3.1.62 "emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.62 (34c1aa36052b1882058f22aa1916437ba0872690)")
gvdb| C linker for the host machine: /home/runner/work/AVM/AVM/emsdk/upstream/emscripten/emcc ld.wasm 19.0.0
gvdb| C compiler for the build machine: cc (gcc 13.3.0 "cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
gvdb| C linker for the build machine: cc ld.bfd 2.42
gvdb| Build targets in project: 0
gvdb| Subproject gvdb finished.

Dependency gvdb found: YES 0.0 (overridden)
Library m found: YES
Run-time dependency libffi found: YES 3.4.6
Run-time dependency zlib found: YES 1.3.1
Run-time dependency intl found: YES
Checking for function "ngettext" with dependency intl: YES 
Checking for function "bind_textdomain_codeset" with dependency intl: YES 
Checking for function "strlcpy" : YES 
Program python3 (packaging) found: NO

meson.build:2422:26: ERROR: python is missing modules: packaging

A full log can be found at /home/runner/work/AVM/AVM/emscripten-libs/glib-2.80.0/build/meson-logs/meson-log.txt
==== CI platform detected, click here for meson-log.txt contents. ====

Error: Process completed with exit code 1.
