    - name: Push WebAssembly to Emulator
      run: |
        adb push i360.js /sdcard/
        adb push i360.wasm /sdcard/
        adb shell ls /sdcard/i360.js /sdcard/i360.wasm || (echo "Failed to push files to emulator" && exit 1)
        echo "Pushed i360.js and i360.wasm to emulator"

    - name: Download WebAssembly Files from Emulator
      run: |
        if ! adb shell getprop | grep -q "ro.build.version.sdk"; then
          echo "Emulator is not running, cannot download files"
          exit 1
        fi
        if ! adb shell "ls /sdcard/i360.js /sdcard/i360.wasm"; then
          echo "i360.js or i360.wasm not found on emulator"
          exit 1
        fi
        echo "Downloading i360.js and i360.wasm from emulator..."
        adb pull /sdcard/i360.js ./i360.js
        adb pull /sdcard/i360.wasm ./i360.wasm
        if [ $? -eq 0 ]; then
          echo "Successfully downloaded i360.js and i360.wasm to workflow directory"
          ls -lh ./i360.js ./i360.wasm
        else
          echo "Failed to download i360.js or i360.wasm"
          exit 1
        fi
        adb shell "rm /sdcard/i360.js /sdcard/i360.wasm"
        echo "Cleaned up i360.js and i360.wasm from emulator"

    - name: Upload WebAssembly Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-files
        path: |
          ./i360.js
          ./i360.wasm
        retention-days: 7
