name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'build-tools;34.0.0 platform-tools platforms;android-34 ndk;25.2.9519653 cmake;3.22.1'
        cmdline-tools-version: 'latest'
        accept-android-sdk-licenses: true

    - name: Verify Android SDK
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "Installed packages:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
        echo "Java version:"
        java -version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        cache-read-only: false

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Verify Gradle Wrapper JAR
      run: |
        ls -lh gradle/wrapper/gradle-wrapper.jar
        file gradle/wrapper/gradle-wrapper.jar

    - name: Check Gradle Version
      run: ./gradlew --version --stacktrace

    - name: Build with diagnostics
      run: |
        ./gradlew assembleDebug --stacktrace --info --no-daemon || \
        (./gradlew androidDependencies --stacktrace --info && exit 1)

    - name: Check Deprecation Warnings
      if: failure()
      run: ./gradlew assembleDebug --warning-mode all --stacktrace --no-daemon

    - name: Upload APK artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifacts
        path: |
          **/build/outputs/apk/**/*.apk
          **/build/outputs/mapping/**/mapping.txt
        if-no-files-found: warn

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: |
          **/build/reports/**
          **/build/outputs/logs/**
          **/build/**/*.html
        if-no-files-found: ignore
