name: Build QEMU WASM for Android

on: [push]

env:
  EMSDK_VERSION: "3.1.62"
  ARTIFACT_RETENTION_DAYS: 7
  PYTHON_VERSION: "3.11"
  QEMU_VERSION: "v9.0.0"
  BUILD_DIR: "${{ github.workspace }}/build"
  STUBS_DIR: "${{ github.workspace }}/stubs"
  LIBS_DIR: "${{ github.workspace }}/emscripten-libs"
  TOTAL_MEMORY: "512MB"
  BASE_CFLAGS: "-s USE_SDL=2 -DNO_FUTEX=1 -D__EMSCRIPTEN__"
  BASE_LDFLAGS: "-s USE_SDL=2 -s ASSERTIONS=1 -s SAFE_HEAP=1 -s USE_PTHREADS=0 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -O3 -flto"

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ${{ env.LIBS_DIR }}
          key: ${{ runner.os }}-deps-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-deps-${{ env.PYTHON_VERSION }}-

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install System Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq \
            build-essential libsdl2-dev libglib2.0-dev libpixman-1-dev \
            ninja-build zlib1g-dev libfdt-dev wget pkg-config git tar xz-utils meson

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Emscripten
        if: steps.cache-deps.outputs.cache-hit != 'true'
        timeout-minutes: 20
        run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ env.EMSDK_VERSION }}
          ./emsdk activate ${{ env.EMSDK_VERSION }}
          echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
          source ./emsdk_env.sh && emcc --version

      - name: Setup Emscripten Environment
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          echo "EMSCRIPTEN=${{ env.EMSDK_PATH }}/upstream/emscripten" >> $GITHUB_ENV
          echo "PATH=${{ env.EMSDK_PATH }}/upstream/bin:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=${{ env.EMSDK_PATH }}/upstream/emscripten/cache/sysroot/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build Emscripten Libraries
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          mkdir -p ${{ env.LIBS_DIR }}
          cd ${{ env.LIBS_DIR }}

          cat > emscripten-cross.txt << 'EOF'
          [binaries]
          c = '${{ env.EMSCRIPTEN }}/emcc'
          cpp = '${{ env.EMSCRIPTEN }}/em++'
          ar = '${{ env.EMSCRIPTEN }}/emar'
          strip = '${{ env.EMSCRIPTEN }}/emstrip'
          pkg-config = 'pkg-config'

          [properties]
          needs_exe_wrapper = true

          [host_machine]
          system = 'emscripten'
          cpu_family = 'wasm32'
          cpu = 'wasm32'
          endian = 'little'
          EOF

          build_lib() {
            local url=$1 name=$2 version=$3 configure_args=$4
            echo "Building $name $version..."
            wget -q "$url" -O "${name}-${version}.tar.gz"
            tar -xzf "${name}-${version}.tar.gz"
            cd "${name}-${version}"
            emconfigure ./configure --prefix="${{ env.EMSCRIPTEN }}/cache/sysroot" $configure_args
            emmake make -j$(nproc) CFLAGS="${{ env.BASE_CFLAGS }}" LDFLAGS="${{ env.BASE_LDFLAGS }}" lib${name}.a
            emmake make install
            cd ..
          }

          build_lib "https://zlib.net/zlib-1.3.1.tar.gz" "zlib" "1.3.1" "--static"
          build_lib "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.gz" "pcre2" "10.44" \
            "--disable-shared --enable-static --disable-jit"

      - name: Fetch QEMU Source
        run: |
          git clone --depth 1 --branch ${{ env.QEMU_VERSION }} https://github.com/qemu/qemu.git || {
            echo "Tag ${{ env.QEMU_VERSION }} not found, falling back to master..."
            git clone https://github.com/qemu/qemu.git
            cd qemu
            git checkout master
          }
          cd qemu
          git log -1

      - name: Patch QEMU Source
        run: |
          cd qemu
          sed -i 's/check_cc_bug() {/check_cc_bug() {\n    return 0/' configure
          echo '#include <errno.h>\n#ifdef __EMSCRIPTEN__\nint memfd_create(const char *name, unsigned int flags) { errno = ENOSYS; return -1; }\n#else\n#error "memfd_create not supported"\n#endif' > util/memfd.c

      - name: Create Stub Headers
        run: |
          mkdir -p ${{ env.STUBS_DIR }}/linux
          cat > ${{ env.STUBS_DIR }}/linux/magic.h << 'EOF'
          #ifndef _LINUX_MAGIC_H
          #define _LINUX_MAGIC_H
          #define TMPFS_MAGIC     0x01021994
          #define RAMFS_MAGIC     0x858458f6
          #define EXT4_SUPER_MAGIC 0xEF53
          #endif
          EOF

      - name: Create Compiler Wrappers
        run: |
          cd qemu
          create_wrapper() {
            local compiler=$1 wrapper_name=$2
            cat > "$wrapper_name" << EOF
          #!/bin/bash
          args=()
          for arg in "\$@"; do
            case "\$arg" in
              "-Werror"|"-fno-gcse"|"-Wold-style-definition"|"-Wtype-limits"|"-m64"|"-mcx16") ;;
              *) args+=("\$arg") ;;
            esac
          done
          exec "${{ env.EMSCRIPTEN }}/$compiler" "\${args[@]}"
          EOF
            chmod +x "$wrapper_name"
          }
          create_wrapper "emcc" "emcc-wrapper.sh"
          create_wrapper "em++" "em++-wrapper.sh"
          echo "EMCC_WRAPPER=$(pwd)/emcc-wrapper.sh" >> $GITHUB_ENV
          echo "EMXX_WRAPPER=$(pwd)/em++-wrapper.sh" >> $GITHUB_ENV

      - name: Configure QEMU for Android
        id: configure
        env:
          CC: "${{ env.EMCC_WRAPPER }}"
          CXX: "${{ env.EMXX_WRAPPER }}"
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemu
          emconfigure ./configure \
            --python=python3 \
            --target-list="i386-softmmu" \
            --disable-xen --disable-user --disable-linux-user --disable-bsd-user \
            --disable-tools --disable-vnc --disable-gtk \
            --cross-prefix="" \
            --cc="$CC" --cxx="$CXX" \
            --extra-cflags="${{ env.BASE_CFLAGS }} -I${{ env.STUBS_DIR }} -Wno-ignored-optimization-argument" \
            --extra-ldflags="${{ env.BASE_LDFLAGS }} -s TOTAL_MEMORY=${{ env.TOTAL_MEMORY }} -s FORCE_FILESYSTEM=1" \
            --disable-werror --disable-stack-protector --disable-docs \
          || { cat config.log; exit 1; }
          echo "CONFIGURE_SUCCEEDED=true" >> $GITHUB_ENV

      - name: Build QEMU WebAssembly for Android
        if: env.CONFIGURE_SUCCEEDED == 'true'
        timeout-minutes: 45
        run: |
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          cd qemu
          export CFLAGS="${{ env.BASE_CFLAGS }} -I${{ env.STUBS_DIR }} -DPCRE2_STATIC -Wno-incompatible-pointer-types"
          export LDFLAGS="${{ env.BASE_LDFLAGS }} -s EXPORTED_FUNCTIONS='[_main,_malloc,_free]' -s EXPORTED_RUNTIME_METHODS='[ccall,cwrap]' -s WASM=1"
          # Build only the WASM file
          emmake make -j$(nproc) V=1 i386-softmmu/qemu-system-i386.wasm \
            || { cat build/meson-logs/meson-log.txt 2>/dev/null || echo "No meson logs available"; exit 1; }
          # Verify WASM output
          [ -f "i386-softmmu/qemu-system-i386.wasm" ] || { echo "Error: WASM file not generated!"; ls -lh i386-softmmu; exit 1; }

      - name: Validate WASM Output
        if: env.CONFIGURE_SUCCEEDED == 'true'
        run: |
          cd qemu/i386-softmmu
          file qemu-system-i386.wasm | grep -q "WebAssembly" || { echo "Error: Not a valid WASM file"; exit 1; }
          echo "WASM file size: $(du -h qemu-system-i386.wasm | cut -f1)"

      - name: Upload Artifact
        if: env.CONFIGURE_SUCCEEDED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: qemu-android-i386-wasm
          path: qemu/i386-softmmu/qemu-system-i386.wasm
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: Cleanup
        if: always()
        run: |
          rm -rf qemu/build qemu/*.o qemu/*.a
