name: Build QEMU WebAssembly (Advanced)
on: [push]
jobs:
  prebuilt-qemu-js:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      QEMU_VERSION: "9.2.0"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
          source ./emsdk_env.sh
          echo "Emscripten version: $(emcc --version)"
        working-directory: .
        timeout-minutes: 10

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-pip ninja-build libsdl2-dev libpixman-1-dev
          pip3 install meson==1.5.0
      - name: Download and Extract QEMU
        run: |
          wget https://download.qemu.org/qemu-${{ env.QEMU_VERSION }}.tar.xz
          tar -xf qemu-${{ env.QEMU_VERSION }}.tar.xz
          mv qemu-${{ env.QEMU_VERSION }} qemu
      - name: Build Qemu.js
        run: |
          cd qemu
          echo "Patching configure to exit after config-host.mak is written..."
          sed -i '/CONFIG_MAK=\$CONFIG_HOST_MAK/a exit 0' configure  # Exit after config-host.mak is fully written
          sed -i '/Unrecognized host OS/ { s/error_exit/#error_exit/; s|$|\necho "Forcing host OS to linux for Emscripten build"\nhost_os=linux|; }' configure
          echo "Creating Emscripten cross-file..."
          cat > emscripten-cross.txt << 'EOF'
          [binaries]
          c = 'emcc'
          cpp = 'em++'
          ar = 'emar'
          strip = 'emstrip'
          pkg-config = 'pkg-config'
          [properties]
          needs_exe_wrapper = true
          [host_machine]
          system = 'emscripten'
          cpu_family = 'wasm'
          cpu = 'wasm32'
          endian = 'little'
          EOF
          echo "Running minimal configure to generate config-host.mak..."
          source "${{ env.EMSDK_PATH }}/emsdk_env.sh"
          emconfigure ./configure --target-list=i386-softmmu --enable-sdl --disable-xen --disable-kvm --disable-vnc --disable-docs --disable-tools --disable-guest-agent || {
            echo "Error: Configure failed!"
            if [ -f config.log ]; then
              echo "Dumping config.log for debugging..."
              cat config.log
            fi
            exit 1
          }
          echo "Verifying config-host.mak..."
          ls -la build/config-host.mak || {
            echo "Error: config-host.mak not generated!"
            exit 1
          }
          echo "Setting up Meson for cross-compilation..."
          meson setup build \
            --cross-file emscripten-cross.txt \
            -Dsdl=enabled \
            -Dxen=disabled \
            -Dkvm=disabled \
            -Dvnc=disabled \
            -Ddocs=disabled \
            -Dtools=disabled \
            -Dguest_agent=disabled \
            -Db_lto=true \
            -Doptimization=2 || {
            echo "Error: Meson setup failed!"
            if [ -f build/meson-logs/meson-log.txt ]; then
              echo "Dumping meson-log.txt for debugging..."
              cat build/meson-logs/meson-log.txt
            fi
            exit 1
          }
          echo "Building with ninja..."
          cd build
          ninja i386-softmmu/qemu-system-i386 CFLAGS="-s WASM=1 -s USE_SDL=2 -s ASSERTIONS=1" LDFLAGS="-s WASM=1 -s USE_SDL=2 -s EXPORTED_FUNCTIONS='[_main]' -s EXPORTED_RUNTIME_METHODS='[ccall,cwrap]' -s ALLOW_MEMORY_GROWTH=1" || {
            echo "Error: Ninja build failed!"
            exit 1
          }
          echo "Build completed, listing generated files..."
          ls -la i386-softmmu/qemu-system-i386*
          if [ -f "i386-softmmu/qemu-system-i386.wasm" ]; then
            FILE_SIZE=$(stat -f%z i386-softmmu/qemu-system-i386.wasm 2>/dev/null || stat -c%s i386-softmmu/qemu-system-i386.wasm)
            echo "qemu-system-i386.wasm size: $FILE_SIZE bytes"
            if [ "$FILE_SIZE" -eq 0 ]; then
              echo "Error: qemu-system-i386.wasm is empty!"
              exit 1
            fi
          else
            echo "Error: qemu-system-i386.wasm not generated!"
            exit 1
          fi
          if [ -f "i386-softmmu/qemu-system-i386.js" ]; then
            FILE_SIZE=$(stat -f%z i386-softmmu/qemu-system-i386.js 2>/dev/null || stat -c%s i386-softmmu/qemu-system-i386.js)
            echo "qemu-system-i386.js size: $FILE_SIZE bytes"
          else
            echo "Warning: qemu-system-i386.js not generated!"
          fi
          mkdir -p ../../qemujs-binaries
          echo "Copying generated files..."
          cp i386-softmmu/qemu-system-i386.js ../../qemujs-binaries/ || echo "Warning: No qemu-system-i386.js found."
          cp i386-softmmu/qemu-system-i386.wasm ../../qemujs-binaries/ || {
            echo "Error: Failed to copy qemu-system-i386.wasm!"
            exit 1
          }
          cp i386-softmmu/*.data ../../qemujs-binaries/ 2>/dev/null || echo "No .data files found."
          echo "Listing copied files in qemujs-binaries..."
          ls -la ../../qemujs-binaries
        working-directory: .

      - name: Verify Files in Binaries Directory
        run: |
          cd qemujs-binaries
          echo "Verifying files in qemujs-binaries..."
          ls -la
          if [ -f "qemu-system-i386.wasm" ]; then
            FILE_SIZE=$(stat -f%z qemu-system-i386.wasm 2>/dev/null || stat -c%s qemu-system-i386.wasm)
            echo "qemu-system-i386.wasm size: $FILE_SIZE bytes"
            if [ "$FILE_SIZE" -eq 0 ]; then
              echo "Error: qemu-system-i386.wasm is empty!"
              exit 1
            fi
          else
            echo "Error: qemu-system-i386.wasm not found in qemujs-binaries!"
            exit 1
          fi
          if [ -f "qemu-system-i386.js" ]; then
            FILE_SIZE=$(stat -f%z qemu-system-i386.js 2>/dev/null || stat -c%s qemu-system-i386.js)
            echo "qemu-system-i386.js size: $FILE_SIZE bytes"
          else
            echo "Warning: qemu-system-i386.js not found."
          fi
        working-directory: .

      - name: Test Qemu.js Binary
        run: |
          cd qemujs-binaries
          echo "Testing Qemu.js binary..."
          if [ -f "qemu-system-i386.js" ]; then
            node qemu-system-i386.js --version || echo "Test may fail as Qemu.js might not support --version directly."
          else
            echo "Warning: qemu-system-i386.js not found, skipping test."
          fi
          if [ -f "qemu-system-i386.wasm" ]; then
            echo "Found qemu-system-i386.wasm."
            ls -la qemu-system-i386.wasm
          else
            echo "Error: qemu-system-i386.wasm not found!"
            exit 1
          fi
        working-directory: .

      - name: Upload Qemu.js Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-js-prebuilt
          path: |
            qemujs-binaries/qemu-system-i386.js
            qemujs-binaries/qemu-system-i386.wasm
            qemujs-binaries/*.data
          if-no-files-found: error
          retention-days: 7

      - name: Cleanup
        run: |
          rm -rf qemu emsdk qemujs-binaries
      - name: Notify Build Status
        if: always()
        run: |
          echo "Pre-built Qemu.js job completed with status: ${{ job.status }}"
