name: Rooted Android Emulator CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  android_test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    # ... (all your previous steps remain unchanged) ...

    - name: Keep Alive with Health Monitoring
      run: |
        echo "Rooted emulator running for 30 minutes with health checks"
        echo "Network logs: /sdcard/network.pcap"
        echo "Use 'adb pull /sdcard/network.pcap' to retrieve logs"
        for i in {1..30}; do
          if ! adb shell getprop | grep -q "ro.build.version.sdk"; then
            echo "Emulator failed at minute $i"
            exit 1
          fi
          if ! adb shell "su -c 'whoami'" | grep -q "root"; then
            echo "Root access lost at minute $i"
            exit 1
          fi
          echo "Health check passed at minute $i"
          sleep 60
        done
        echo "Emulator ran successfully for 30 minutes"

    - name: Download Network Capture File
      run: |
        if ! adb shell getprop | grep -q "ro.build.version.sdk"; then
          echo "Emulator is not running, cannot download network.pcap"
          exit 1
        fi
        if ! adb shell "ls /sdcard/network.pcap"; then
          echo "network.pcap not found on emulator"
          exit 1
        fi
        echo "Downloading network.pcap from emulator..."
        adb pull /sdcard/network.pcap ./network.pcap
        if [ $? -eq 0 ]; then
          echo "Successfully downloaded network.pcap to workflow directory"
          ls -lh ./network.pcap
        else
          echo "Failed to download network.pcap"
          exit 1
        fi
        adb shell "rm /sdcard/network.pcap"
        echo "Cleaned up network.pcap from emulator"

    - name: Upload Network Capture as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: network-capture
        path: ./network.pcap
        retention-days: 7
