name: Rooted Android Emulator with Web Access

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  rooted_emulator:
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install ARM64 system image
      run: |
        sdkmanager --install "system-images;android-30;google_apis;arm64-v8a"
        echo "arm64 system image installed"

    - name: Create and start rooted AVD
      uses: reactivecircus/android-emulator-runner@v2
      id: emulator
      with:
        api-level: 30
        arch: arm64-v8a
        profile: "Nexus 5X"
        force-avd-creation: true
        emulator-options: -no-window -no-snapshot -gpu swiftshader_indirect -noaudio -no-boot-anim -read-only -writable-system -accel off
        disable-animations: true
        script: |
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          echo "Device booted, beginning root process..."
          adb root
          adb remount
          adb shell avbctl disable-verification
          adb reboot
          echo "Waiting for reboot..."
          adb wait-for-device
          adb root
          adb remount
          echo "Emulator ready and rooted"

    - name: Install required packages
      run: |
        # Install homebrew packages for web access
        brew install scrcpy websockify novnc

    - name: Setup web access and monitoring
      run: |
        # Start scrcpy server
        adb forward tcp:8888 localabstract:scrcpy
        
        # Start websockify and noVNC
        websockify --web /usr/local/share/novnc 6080 localhost:8888 &
        
        # Start network monitoring
        adb shell su -c "tcpdump -i any -s 0 -w /sdcard/network.pcap &"
        
        # Start HTTP server for logs
        python3 -m http.server 8000 &
        
        echo "Web interface: http://localhost:6080/vnc.html"
        echo "Network logs: http://localhost:8000/network.pcap"

    - name: Keep alive for debugging
      run: |
        echo "Emulator will remain active for 30 minutes"
        sleep 1800
