name: Build QEMU WebAssembly
on: [push, workflow_dispatch]
jobs:
  build-qemu-wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      QEMU_VERSION: "9.2.0"
      EMSCRIPTEN_VERSION: "latest"
      BUILD_DIR: "qemu-build-wasm"
      OUTPUT_DIR: "qemu-wasm-dist"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            git \
            python3 \
            python3-pip \
            ninja-build \
            libglib2.0-dev \
            libpixman-1-dev \
            libsdl2-dev \
            pkg-config \
            wget \
            xz-utils
          sudo pip3 install meson==1.5.0

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: 'emsdk_cache'

      - name: Download QEMU Source
        run: |
          wget -q --show-progress https://download.qemu.org/qemu-${{ env.QEMU_VERSION }}.tar.xz
          tar -xf qemu-${{ env.QEMU_VERSION }}.tar.xz
          mv qemu-${{ env.QEMU_VERSION }} qemu-src
          rm qemu-${{ env.QEMU_VERSION }}.tar.xz

      - name: Patch QEMU Source
        run: |
          cd qemu-src
          # Patch configure to skip unsupported checks
          sed -i 's/check_define __linux__/true || &/' configure
          sed -i 's/check_define __FreeBSD__/true || &/' configure
          
          # Create minimal configuration for WASM
          cat > config-host.mak << 'EOF'
          CONFIG_SDL=y
          CONFIG_XEN=n
          CONFIG_KVM=n
          CONFIG_VNC=n
          CONFIG_DOCS=n
          CONFIG_TOOLS=n
          CONFIG_GUEST_AGENT=n
          EOF

      - name: Create Emscripten Build Environment
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cd ${{ env.BUILD_DIR }}
          
          cat > build.sh << 'EOF'
          #!/bin/bash
          set -ex
          
          # Source Emscripten environment
          source "$EMSDK/emsdk_env.sh"
          
          # Configure with minimal options
          ../qemu-src/configure \
            --cc=emcc \
            --host-cc=emcc \
            --ar=emar \
            --target-list=i386-softmmu \
            --enable-sdl \
            --disable-xen \
            --disable-kvm \
            --disable-vnc \
            --disable-docs \
            --disable-tools \
            --disable-guest-agent \
            --extra-cflags="-s WASM=1 -s USE_SDL=2 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1" \
            --extra-ldflags="-s WASM=1 -s USE_SDL=2 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1"
          
          # Build core components
          make -j$(nproc) qemu-system-i386
          
          # Rename output for WASM
          mv qemu-system-i386 qemu-system-i386.js
          EOF
          
          chmod +x build.sh

      - name: Build QEMU
        run: |
          cd ${{ env.BUILD_DIR }}
          ./build.sh
          
          # Verify output
          if [ -f "qemu-system-i386.js" ]; then
            echo "Build successful"
            mkdir -p ${{ env.OUTPUT_DIR }}
            cp qemu-system-i386.* ${{ env.OUTPUT_DIR }}/
          else
            echo "Build failed"
            exit 1
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-wasm-build
          path: ${{ env.OUTPUT_DIR }}/*
          if-no-files-found: error
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          rm -rf qemu-src ${{ env.BUILD_DIR }} ${{ env.OUTPUT_DIR }}
