#!/bin/bash

# Update & Install Dependencies
sudo apt update && sudo apt install -y waydroid adb wget unzip net-tools novnc websockify

# Initialize Waydroid (Android VM)
sudo waydroid init

# Start Waydroid Container
sudo systemctl start waydroid-container
waydroid session start &
sleep 10

# Enable Root Access
sudo waydroid shell "su -c 'setenforce 0'"

# Install APK File (Specify Your APK Path)
APK_PATH="/path/to/your.apk"
adb connect localhost:5555
adb install "$APK_PATH"

# Capture Network Logs using tcpdump
sudo waydroid shell "su -c 'tcpdump -i any -w /sdcard/network_log.pcap'" &

# Start VNC Server for Web Access
waydroid prop set persist.waydroid.vnc 1
waydroid session stop
waydroid session start &
sleep 5
websockify --web /usr/share/novnc/ 6080 localhost:5900 &

echo "Android VM is accessible via: http://localhost:6080"
echo "Network logs saved in: /sdcard/network_log.pcap"
