name: Build QEMU WebAssembly
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Fail after 45 minutes
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 libsdl2-dev
      - name: Download QEMU Source
        run: |
          wget https://download.qemu.org/qemu-8.2.0.tar.xz
          tar -xf qemu-8.2.0.tar.xz
          mv qemu-8.2.0 qemu
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        working-directory: .
      - name: Configure and Build QEMU
        run: |
          cd qemu
          ./configure --target-list=i386-softmmu --cc=emcc --cxx=em++ --extra-cflags="-s USE_SDL=2" --extra-ldflags="-s USE_SDL=2 -s EXPORTED_FUNCTIONS='[_main]' -s EXPORTED_RUNTIME_METHODS=['ccall','cwrap']"
          emmake make -j2  # Limit to 2 jobs
        working-directory: .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Upgrade to v4
        with:
          name: qemu-wasm
          path: qemu/i386-softmmu/qemu-system-i386.*
          if-no-files-found: error  # Fail if no files match
