name: Android Emulator with Root Access

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  android_emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install system image
      run: |
        sdkmanager --install "system-images;android-30;google_apis;x86_64"
        echo "System image installed"

    - name: Create and configure AVD
      run: |
        echo "no" | avdmanager create avd \
          --name test \
          --package "system-images;android-30;google_apis;x86_64" \
          --abi "x86_64" \
          --device "pixel_4"
        
        # Configure AVD for better performance
        echo "hw.ramSize=2048" >> ~/.android/avd/test.avd/config.ini
        echo "hw.gpu.enabled=yes" >> ~/.android/avd/test.avd/config.ini
        echo "hw.gpu.mode=auto" >> ~/.android/avd/test.avd/config.ini
        echo "hw.keyboard=yes" >> ~/.android/avd/test.avd/config.ini
        echo "vm.heapSize=256" >> ~/.android/avd/test.avd/config.ini

    - name: Start emulator with KVM
      run: |
        sudo apt-get -qq install qemu-kvm
        sudo chmod 777 /dev/kvm
        
        $ANDROID_SDK_ROOT/emulator/emulator \
          -avd test \
          -no-window \
          -no-audio \
          -no-boot-anim \
          -gpu auto \
          -accel on \
          -writable-system \
          -qemu -m 2048 -enable-kvm &
        
        adb wait-for-device
        echo "Emulator started successfully"

    - name: Root the emulator
      run: |
        adb root
        adb remount
        adb shell avbctl disable-verification
        adb reboot
        adb wait-for-device
        adb root
        adb remount
        echo "Emulator rooted successfully"

    - name: Install APKs and setup monitoring
      run: |
        # Install your APK
        adb install app-debug.apk
        
        # Install monitoring tools
        adb push tcpdump /data/local/tmp/tcpdump
        adb shell chmod +x /data/local/tmp/tcpdump
        
        # Start network monitoring
        adb shell /data/local/tmp/tcpdump -i any -s 0 -w /sdcard/network.pcap &
        
        echo "Network monitoring started"

    - name: Keep alive
      run: |
        echo "Emulator will remain active for 15 minutes"
        sleep 900
