name: Android Emulator CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  android_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools: 'latest'
        build-tools: '34.0.0'
        platform-tools: 'latest'
        platforms: 'android-30'
        emulator: 'latest'
        ndk: 'none'

    - name: Install system image
      run: |
        # Accept licenses first
        yes | sdkmanager --licenses || true
        sdkmanager --install "system-images;android-30;google_apis;x86_64"
        sdkmanager --list

    - name: Create Android Virtual Device
      run: |
        # Create AVD directory if it doesn't exist
        mkdir -p ~/.android/avd

        # Create the AVD with more reliable parameters
        echo "no" | avdmanager create avd \
          --force \
          --name "android-ci" \
          --package "system-images;android-30;google_apis;x86_64" \
          --abi "x86_64" \
          --device "pixel_4"

        # Verify AVD was created
        if [ ! -f ~/.android/avd/android-ci.avd/config.ini ]; then
          echo "AVD configuration file not found!"
          ls -la ~/.android/avd/
          exit 1
        fi

        # Configure AVD settings
        echo "hw.ramSize=2048" >> ~/.android/avd/android-ci.avd/config.ini
        echo "hw.gpu.enabled=yes" >> ~/.android/avd/android-ci.avd/config.ini
        echo "hw.gpu.mode=host" >> ~/.android/avd/android-ci.avd/config.ini
        echo "hw.keyboard=yes" >> ~/.android/avd/android-ci.avd/config.ini
        echo "vm.heapSize=256" >> ~/.android/avd/android-ci.avd/config.ini
        echo "disk.dataPartition.size=2G" >> ~/.android/avd/android-ci.avd/config.ini

        echo "AVD created successfully"

    - name: Setup KVM acceleration
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq qemu-kvm
        sudo chmod 777 /dev/kvm
        groups
        echo "KVM acceleration ready"

    - name: Start emulator
      run: |
        # Start emulator in background
        nohup $ANDROID_SDK_ROOT/emulator/emulator \
          -avd android-ci \
          -no-window \
          -no-audio \
          -no-boot-anim \
          -gpu host \
          -accel on \
          -writable-system \
          -qemu -m 2048 -enable-kvm > /dev/null 2>&1 &

        # Wait for emulator to start
        adb wait-for-device
        echo "Emulator started. Waiting for boot completion..."
        
        # Wait for boot completion
        while true; do
          boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
          if [ "$boot_completed" == "1" ]; then
            break
          fi
          sleep 5
          echo "Waiting for emulator to boot..."
        done
        
        echo "Emulator is ready"

    - name: Basic device verification
      run: |
        adb shell getprop
        adb devices -l
        adb shell settings put global window_animation_scale 0
        adb shell settings put global transition_animation_scale 0
        adb shell settings put global animator_duration_scale 0

    - name: Keep emulator running
      run: |
        echo "Emulator will stay active for 15 minutes"
        sleep 900
